" Load Fucntions
runtime! functions.vim
runtime! command.vim
runtime! filetype.vim


" Color
set t_Co=256
set background=dark
if filereadable(GetIcebergPath())
    colorscheme iceberg
endif


" General
set number
set title
set wildmenu
set history=10000
set showmatch
set matchtime=1
set mouse=""
set fileformats=unix,dos,mac
set encoding=utf-8
set fileencodings=utf-8,iso-2022-jp,euc-jp,sjis
set backspace=indent,eol,start
set modeline


" Indent
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set autoindent
set smartindent


" Search
set ignorecase
set smartcase
set wrapscan
set incsearch
set hlsearch


" Backup
set nowritebackup
set nobackup
set noswapfile


" Display
set noerrorbells
set cmdheight=1
set laststatus=2
set ambiwidth=double
set showcmd
set display=lastline


" Terminal
if has("win32")
    set termwintype=winpty
endif


" GVim configuration
if has("gui_running")
    set guioptions-=T
    set guioptions-=m
    set guioptions+=a
    set guioptions+=R
endif


" Load After Configuration
runtime! plugin.vim
runtime! keymapping.vim


" Load Local Configuration
let $LOCAL_VIMRC = expand(GetVimConfigDir() . "/vimrc_local")
if filereadable($LOCAL_VIMRC)
    source $LOCAL_VIMRC
endif
