alias l="ls --color=auto"
alias ls="ls --color=auto"
alias la="ls -a --color=auto"
alias ll="ls -al --color=auto"

alias cl="clear"
alias cfg="cd ~/Config"

alias cp="cp -i"
alias mv="mv -i"
alias rm="rm -i"

alias gst="git status"
alias gl="git log"
alias ga="git add"
alias gc="git commit"
alias gca="git commit --amend"
alias gr="git reset"
alias gd="git diff"
alias gdc="git diff --cached"
alias gs="git switch"
alias gsc="git switch -c"
alias gb="git branch"
alias gm="git merge"
alias gp="git pull"

alias cdg="cd-gitroot"
