export LC_ALL=ja_JP.UTF-8
export LC_MESSAGES=ja_JP.UTF-8
export LANG=ja_JP.UTF-8

export DIRSTACKSIZE=50
export HISTSIZE=10000
export HISTFILESIZE=20000
export HISTFILE=~/.zsh_history

export ZPLUG_HOME=~/.zplug
export ZSH_LOCAL_CONFIG=~/local_config/zshrc

export GTK_IM_MODULE=fcitx5
export QT_IM_MODULE=fcitx5
export XMODIFIERS=@im=fcitx5
