# vim: ft=zsh

for config_file in ~/.zsh/config/*.zsh; do
    source $config_file
done

# initilize config 
function init_config(){
    # install zplug
    if [ -d $ZPLUG_HOME ];then return; fi
    git clone https://github.com/zplug/zplug $ZPLUG_HOME

    # install iceberg(vim colorscheme)
    if [ -f ~/.vim/colors/iceberg.vim ];then return; fi
    curl -fLo ~/.vim/colors/iceberg.vim --create-dirs \
        https://raw.githubusercontent.com/cocopon/iceberg.vim/master/colors/iceberg.vim

    # install vim-plug(vim plugin manager)
    if [ -f ~/.vim/autoload/plug.vim ];then return; fi
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
}

# define zsh plugins with ZPLUG
if [ -d $ZPLUG_HOME ];then
    source $ZPLUG_HOME/init.zsh

    # plugins
    zplug "zsh-users/zsh-syntax-highlighting", defer:2
    zplug "zsh-users/zsh-autosuggestions"
    zplug "mollifier/cd-gitroot"

    # Then, source plugins and add commands to $PATH
    zplug load
fi

# color and complite
autoload -Uz colors
autoload -Uz compinit
autoload -Uz add-zsh-hook
autoload -Uz vcs_info

compinit
colors

# vim mode
bindkey -v

# setoptions
setopt share_history
setopt histignorealldups
setopt auto_cd
setopt auto_pushd
setopt pushd_ignore_dups
setopt correct
setopt prompt_subst

add-zsh-hook precmd set_command_result
add-zsh-hook precmd vcs_info

zstyle ':vcs_info:git:*' check-for-changes true
zstyle ':vcs_info:git:*' stagedstr "staged"
zstyle ':vcs_info:git:*' unstagedstr "changed"
zstyle ':vcs_info:*' formats "%b:%c%u"
zstyle ':vcs_info:*' actionformats "%b:action:%a"

# prompt
PROMPT='`echo_left_prompt`'

# load local config
[ -r ~/.dotfiles.local/zshrc ] \
    && . ~/.dotfiles.local/zshrc \
    || :
